/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthResult = { 'ok' : string } |
  { 'err' : string };
export interface CheckInPublic {
  'participant' : string,
  'matchId' : string,
  'timestamp' : bigint,
}
export interface MatchEntry {
  'mutual' : boolean,
  'matched' : Principal,
  'profile' : UserProfile,
}
export interface MatchPublic {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'missing' : bigint,
  'createdAt' : bigint,
  'time' : string,
  'sport' : string,
  'requirements' : [] | [string],
  'location' : string,
}
export type MatchResult = { 'ok' : null } |
  { 'err' : string };
export interface Message {
  'id' : string,
  'to' : Principal,
  'from' : Principal,
  'createdAt' : bigint,
  'text' : string,
}
export interface NewsItem {
  'id' : string,
  'url' : string,
  'title' : string,
  'source' : string,
  'publishedAt' : string,
  'description' : string,
  'sport' : string,
  'imageUrl' : string,
}
export interface PlayerRank {
  'totalRatings' : bigint,
  'totalMatches' : bigint,
  'showUpCount' : bigint,
  'userPrincipal' : Principal,
  'lastActive' : bigint,
  'avgRating' : number,
}
export interface PlayerRating {
  'raterPrincipal' : Principal,
  'createdAt' : bigint,
  'score' : bigint,
  'comment' : string,
  'matchId' : string,
  'ratedPrincipal' : Principal,
}
export interface ProfileEntry { 'owner' : Principal, 'profile' : UserProfile }
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'avatarUrl' : string,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'createMatch' : ActorMethod<
    [string, string, string, string, bigint, [] | [string]],
    string
  >,
  'deleteExpiredMatches' : ActorMethod<[Array<string>], bigint>,
  'deleteMatch' : ActorMethod<[string], MatchResult>,
  'getAllMatches' : ActorMethod<[], Array<MatchPublic>>,
  'getAllProfiles' : ActorMethod<[], Array<ProfileEntry>>,
  'getAllRankings' : ActorMethod<[], Array<PlayerRank>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheckIns' : ActorMethod<[string], Array<CheckInPublic>>,
  'getHotNews' : ActorMethod<[], Array<NewsItem>>,
  'getMatchParticipants' : ActorMethod<[string], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getMyMatches' : ActorMethod<[], Array<MatchEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPlayerRank' : ActorMethod<[Principal], [] | [PlayerRank]>,
  'getRatingsForPlayer' : ActorMethod<[Principal], Array<PlayerRating>>,
  'hasCheckedIn' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMatchParticipant' : ActorMethod<[string], boolean>,
  'joinMatch' : ActorMethod<[string], undefined>,
  'leaveMatch' : ActorMethod<[string], undefined>,
  'loginUser' : ActorMethod<[string, string], AuthResult>,
  'logoutUser' : ActorMethod<[string], undefined>,
  'matchWithUser' : ActorMethod<[Principal], undefined>,
  'ratePlayer' : ActorMethod<
    [string, Principal, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerMe' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string, string], AuthResult>,
  'searchMatchesByLocation' : ActorMethod<[string], Array<MatchPublic>>,
  'searchMatchesBySport' : ActorMethod<[string], Array<MatchPublic>>,
  'sendMessage' : ActorMethod<[Principal, string], string>,
  'updateMyProfile' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'validateSession' : ActorMethod<[string], [] | [string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];