/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const MatchPublic = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'missing' : IDL.Int,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'sport' : IDL.Text,
  'requirements' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const ProfileEntry = IDL.Record({
  'owner' : IDL.Principal,
  'profile' : UserProfile,
});
export const PlayerRank = IDL.Record({
  'totalRatings' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'showUpCount' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
  'lastActive' : IDL.Int,
  'avgRating' : IDL.Float64,
});
export const CheckInPublic = IDL.Record({
  'participant' : IDL.Text,
  'matchId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const NewsItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
  'sport' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});
export const MatchEntry = IDL.Record({
  'mutual' : IDL.Bool,
  'matched' : IDL.Principal,
  'profile' : UserProfile,
});
export const PlayerRating = IDL.Record({
  'raterPrincipal' : IDL.Principal,
  'createdAt' : IDL.Int,
  'score' : IDL.Nat,
  'comment' : IDL.Text,
  'matchId' : IDL.Text,
  'ratedPrincipal' : IDL.Principal,
});
export const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createMatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteExpiredMatches' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'deleteMatch' : IDL.Func([IDL.Text], [MatchResult], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(ProfileEntry)], ['query']),
  'getAllRankings' : IDL.Func([], [IDL.Vec(PlayerRank)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheckIns' : IDL.Func([IDL.Text], [IDL.Vec(CheckInPublic)], ['query']),
  'getHotNews' : IDL.Func([], [IDL.Vec(NewsItem)], []),
  'getMatchParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMyMatches' : IDL.Func([], [IDL.Vec(MatchEntry)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPlayerRank' : IDL.Func([IDL.Principal], [IDL.Opt(PlayerRank)], ['query']),
  'getRatingsForPlayer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlayerRating)],
      ['query'],
    ),
  'hasCheckedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMatchParticipant' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func([IDL.Text], [], []),
  'leaveMatch' : IDL.Func([IDL.Text], [], []),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'logoutUser' : IDL.Func([IDL.Text], [], []),
  'matchWithUser' : IDL.Func([IDL.Principal], [], []),
  'ratePlayer' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerMe' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
  'searchMatchesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MatchPublic)],
      ['query'],
    ),
  'searchMatchesBySport' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MatchPublic)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const MatchPublic = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'missing' : IDL.Int,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'sport' : IDL.Text,
    'requirements' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ProfileEntry = IDL.Record({
    'owner' : IDL.Principal,
    'profile' : UserProfile,
  });
  const PlayerRank = IDL.Record({
    'totalRatings' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'showUpCount' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
    'lastActive' : IDL.Int,
    'avgRating' : IDL.Float64,
  });
  const CheckInPublic = IDL.Record({
    'participant' : IDL.Text,
    'matchId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const NewsItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
    'sport' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  const MatchEntry = IDL.Record({
    'mutual' : IDL.Bool,
    'matched' : IDL.Principal,
    'profile' : UserProfile,
  });
  const PlayerRating = IDL.Record({
    'raterPrincipal' : IDL.Principal,
    'createdAt' : IDL.Int,
    'score' : IDL.Nat,
    'comment' : IDL.Text,
    'matchId' : IDL.Text,
    'ratedPrincipal' : IDL.Principal,
  });
  const AuthResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createMatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteExpiredMatches' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'deleteMatch' : IDL.Func([IDL.Text], [MatchResult], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(MatchPublic)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(ProfileEntry)], ['query']),
    'getAllRankings' : IDL.Func([], [IDL.Vec(PlayerRank)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheckIns' : IDL.Func([IDL.Text], [IDL.Vec(CheckInPublic)], ['query']),
    'getHotNews' : IDL.Func([], [IDL.Vec(NewsItem)], []),
    'getMatchParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMyMatches' : IDL.Func([], [IDL.Vec(MatchEntry)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPlayerRank' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerRank)],
        ['query'],
      ),
    'getRatingsForPlayer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlayerRating)],
        ['query'],
      ),
    'hasCheckedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMatchParticipant' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func([IDL.Text], [], []),
    'leaveMatch' : IDL.Func([IDL.Text], [], []),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'logoutUser' : IDL.Func([IDL.Text], [], []),
    'matchWithUser' : IDL.Func([IDL.Principal], [], []),
    'ratePlayer' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerMe' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [AuthResult], []),
    'searchMatchesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MatchPublic)],
        ['query'],
      ),
    'searchMatchesBySport' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MatchPublic)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };