/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlayerRating {
    raterPrincipal: Principal;
    createdAt: bigint;
    score: bigint;
    comment: string;
    matchId: string;
    ratedPrincipal: Principal;
}
export type MatchResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface MatchEntry {
    mutual: boolean;
    matched: Principal;
    profile: UserProfile;
}
export interface MatchPublic {
    id: string;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    missing: bigint;
    createdAt: bigint;
    time: string;
    sport: string;
    requirements?: string;
    location: string;
}
export interface Message {
    id: string;
    to: Principal;
    from: Principal;
    createdAt: bigint;
    text: string;
}
export interface CheckInPublic {
    participant: string;
    matchId: string;
    timestamp: bigint;
}
export interface ProfileEntry {
    owner: Principal;
    profile: UserProfile;
}
export type AuthResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface NewsItem {
    id: string;
    url: string;
    title: string;
    source: string;
    publishedAt: string;
    description: string;
    sport: string;
    imageUrl: string;
}
export interface UserProfile {
    bio: string;
    name: string;
    avatarUrl: string;
    skills: Array<string>;
}
export interface PlayerRank {
    totalRatings: bigint;
    totalMatches: bigint;
    showUpCount: bigint;
    userPrincipal: Principal;
    lastActive: bigint;
    avgRating: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkIn(matchId: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createMatch(sport: string, title: string, time: string, location: string, missing: bigint, requirements: string | null): Promise<string>;
    deleteExpiredMatches(ids: Array<string>): Promise<bigint>;
    deleteMatch(id: string): Promise<MatchResult>;
    getAllMatches(): Promise<Array<MatchPublic>>;
    getAllProfiles(): Promise<Array<ProfileEntry>>;
    getAllRankings(): Promise<Array<PlayerRank>>;
    getCallerUserRole(): Promise<UserRole>;
    getCheckIns(matchId: string): Promise<Array<CheckInPublic>>;
    getHotNews(): Promise<Array<NewsItem>>;
    getMatchParticipants(id: string): Promise<Array<Principal>>;
    getMessages(withUser: Principal): Promise<Array<Message>>;
    getMyMatches(): Promise<Array<MatchEntry>>;
    getMyProfile(): Promise<UserProfile | null>;
    getPlayerRank(user: Principal): Promise<PlayerRank | null>;
    getRatingsForPlayer(user: Principal): Promise<Array<PlayerRating>>;
    hasCheckedIn(matchId: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isMatchParticipant(id: string): Promise<boolean>;
    joinMatch(id: string): Promise<void>;
    leaveMatch(id: string): Promise<void>;
    loginUser(username: string, password: string): Promise<AuthResult>;
    logoutUser(token: string): Promise<void>;
    matchWithUser(target: Principal): Promise<void>;
    ratePlayer(matchId: string, ratedPrincipal: Principal, score: bigint, comment: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerMe(): Promise<void>;
    registerUser(username: string, password: string): Promise<AuthResult>;
    searchMatchesByLocation(location: string): Promise<Array<MatchPublic>>;
    searchMatchesBySport(sport: string): Promise<Array<MatchPublic>>;
    sendMessage(to: Principal, text: string): Promise<string>;
    updateMyProfile(name: string, bio: string, avatarUrl: string, skills: Array<string>): Promise<void>;
    validateSession(token: string): Promise<string | null>;
}
import type { AuthResult as _AuthResult, MatchPublic as _MatchPublic, MatchResult as _MatchResult, PlayerRank as _PlayerRank, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMatch(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteExpiredMatches(arg0: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpiredMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpiredMatches(arg0);
            return result;
        }
    }
    async deleteMatch(arg0: string): Promise<MatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return from_candid_MatchResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return from_candid_MatchResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMatches(): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<ProfileEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return result;
        }
    }
    async getAllRankings(): Promise<Array<PlayerRank>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRankings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRankings();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCheckIns(arg0: string): Promise<Array<CheckInPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckIns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckIns(arg0);
            return result;
        }
    }
    async getHotNews(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHotNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHotNews();
            return result;
        }
    }
    async getMatchParticipants(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchParticipants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchParticipants(arg0);
            return result;
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyMatches(): Promise<Array<MatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMatches();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerRank(arg0: Principal): Promise<PlayerRank | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRank(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRank(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingsForPlayer(arg0: Principal): Promise<Array<PlayerRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForPlayer(arg0);
            return result;
        }
    }
    async hasCheckedIn(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCheckedIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCheckedIn(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isMatchParticipant(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMatchParticipant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMatchParticipant(arg0);
            return result;
        }
    }
    async joinMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatch(arg0);
            return result;
        }
    }
    async leaveMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveMatch(arg0);
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_AuthResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_AuthResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async logoutUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutUser(arg0);
            return result;
        }
    }
    async matchWithUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.matchWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matchWithUser(arg0);
            return result;
        }
    }
    async ratePlayer(arg0: string, arg1: Principal, arg2: bigint, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.ratePlayer(arg0, arg1, arg2, arg3);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ratePlayer(arg0, arg1, arg2, arg3);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerMe(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMe();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMe();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return from_candid_AuthResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return from_candid_AuthResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchMatchesByLocation(arg0: string): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMatchesByLocation(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMatchesByLocation(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchMatchesBySport(arg0: string): Promise<Array<MatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMatchesBySport(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMatchesBySport(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MatchPublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchPublic): MatchPublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MatchResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchResult): MatchResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerRank]): PlayerRank | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    missing: bigint;
    createdAt: bigint;
    time: string;
    sport: string;
    requirements: [] | [string];
    location: string;
}): {
    id: string;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    missing: bigint;
    createdAt: bigint;
    time: string;
    sport: string;
    requirements?: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        participants: value.participants,
        missing: value.missing,
        createdAt: value.createdAt,
        time: value.time,
        sport: value.sport,
        requirements: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.requirements)),
        location: value.location
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchPublic>): Array<MatchPublic> {
    return value.map((x)=>from_candid_MatchPublic_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
