export type Lang = "vi" | "en";

export const translations = {
  vi: {
    // Nav
    findMatch: "Tìm trận",
    createMatch: "Tạo trận",
    login: "Đăng nhập",
    logout: "Đăng xuất",
    profile: "Hồ sơ",
    online: "Trực tuyến",
    offline: "Ngoại tuyến",
    notifications: "Thông báo",

    // Hero
    heroTitle: "Kết nối đồng đội,",
    heroTitle2: "chinh phục đam mê",
    heroSub: "Tìm đồng đội thể thao gần bạn — nhanh chóng, dễ dàng, vui vẻ.",
    heroCreate: "Tạo trận ngay",
    heroFind: "Tìm trận",

    // Match
    matchOpen: "Trận đang mở",
    matchFull: "Đã đủ quân",
    missingCount: "người thiếu",
    joinMatch: "Tham gia trận này",
    leaveMatch: "Rời trận",
    deleteMatch: "Xóa trận",
    shareMatch: "Chia sẻ trận",
    viewDetail: "Xem chi tiết",
    joinSuccess: "Tham gia trận thành công! 🎉",
    leaveSuccess: "Rời trận thành công!",
    deleteSuccess: "Trận đã xóa thành công",
    createSuccess: "Tạo trận thành công! 🎉",
    copiedLink: "Đã sao chép link trận! 🔗",
    cantJoin: "Không thể tham gia trận",
    cantLeave: "Không thể rời trận",
    needLoginCreate: "Bạn cần đăng nhập để tạo trận.",
    needLoginSave: "Vui lòng đăng nhập để lưu hồ sơ.",
    today: "📅 Hôm nay",
    thisWeek: "📆 Tuần này",
    weekend: "🎉 Cuối tuần",
    all: "⏰ Tất cả",
    todayMatches: "Trận hôm nay",
    noMatches: "Không có trận nào",
    collapse: "Thu gọn",

    // Create form
    sport: "Môn thể thao",
    chooseSport: "Chọn môn thể thao...",
    chooseSportShort: "Chọn môn...",
    title: "Tiêu đề trận",
    titlePlaceholder: "VD: Bóng đá chiều thứ 6",
    time: "Thời gian",
    location: "Địa điểm",
    locationPlaceholder: "Hoặc nhập địa chỉ thủ công...",
    missingPlayers: "Số người thiếu",
    howManyMissing: "Cần thêm bao nhiêu người?",
    requirements: "Yêu cầu đồng đội",
    requirementsPlaceholder: "VD: Cần người chơi có kinh nghiệm, tính cách thân thiện, tuổi 18–25, biết phối hợp đồng đội...",
    requirementsHint: "Yêu cầu này sẽ hiển thị trên thẻ trận để người tham gia có thể đọc và quyết định tham gia.",
    submitCreate: "Gửi / Tạo Trận",
    chooseSportFirst: "Vui lòng chọn môn thể thao",
    chooseTimeFirst: "Vui lòng chọn thời gian",
    chooseLocationFirst: "Vui lòng nhập địa điểm",
    missingPositive: "Số người thiếu phải là số nguyên dương",
    useMyLocation: "📍 Dùng vị trí của tôi",
    closePitchList: "Đóng danh sách sân",
    nearestFirst: " — gần nhất trước",
    locationDenied: "Bạn đã từ chối quyền truy cập vị trí",
    locationFailed: "Không thể lấy vị trí. Thử lại sau.",
    gpsNotSupported: "Thiết bị không hỗ trợ GPS",
    locating: "Đang xác định...",
    openMap: "Mở bản đồ",
    chooseDistrict: "Chọn quận/huyện...",

    // Profile
    noName: "Chưa có tên",
    shortBio: "Mô tả ngắn về bản thân...",
    save: "Lưu",
    saveSuccess: "Đã lưu hồ sơ thành công!",
    uploadPhoto: "📷 Upload ảnh",
    autoGenerate: "🎲 Tạo tự động",
    student: "Sinh viên",
    skills: "Kỹ năng",

    // Check-in
    checkin: "✓ Check-in",
    showQR: "Hiển thị mã QR Check-in",
    pasteQR: "Dán mã QR vào đây...",
    invalidQR: "Mã QR không hợp lệ",
    wrongMatchQR: "Mã QR không thuộc trận này",
    checkinSuccess: "Đã check-in thành công! ✅",
    alreadyCheckin: "Đã check-in rồi. Bạn đã check-in trước đó rồi!",
    cantCheckin: "Không thể truy cập camera. Vui lòng cấp quyền camera.",

    // Rating
    sendRating: "Gửi đánh giá",
    ratingComment: "Nhận xét (tùy chọn)...",
    ratingSuccess: "Đã gửi đánh giá!",
    alreadyRated: "Đã đánh giá!",
    cantRate: "Không thể đánh giá.",

    // Match with / ranking
    matched: "Match ✓",
    matchedDone: "✓ Matched!",
    justNow: "Vừa xong",
    searchByName: "Tìm kiếm theo tên...",
    clearSearch: "Xóa tìm kiếm",

    // Chat
    messages: "Tin nhắn",
    sendMessage: "Gửi",
    messageInput: "Nhập tin nhắn...",
    selectContact: "Chọn người để nhắn tin",
    searchUser: "🔍 Tìm người dùng...",
    noContacts: "Chưa có người chơi cùng trận",
    noResults: "Không tìm thấy người dùng",
    icebreaker: "🎯 Phá băng nào!",
    icebreakerSub: "Chọn câu hỏi để bắt đầu",
    sent: "✓ Đã gửi",
    seen: "✓✓ Đã xem",
    newMessage: "Tin nhắn mới 💬",

    // News
    news: "Tin thể thao nổi bật",
    close: "Đóng",

    // Sport descriptions
    soccerDesc: "Môn thể thao vua với 11 người mỗi đội, kết hợp kỹ thuật cá nhân và teamwork.",
    futsalDesc: "Futsal sân nhỏ, nhịp độ cao, kỹ thuật tinh tế và cần phối hợp tốt.",
    basketballDesc: "Môn bóng rổ nhanh, cần phối hợp đồng đội và kỹ năng ném bóng.",
    volleyballDesc: "Môn bóng chuyền cần teamwork và phản xạ tốt, phổ biến trong sinh viên.",
    badmintonDesc: "Cầu lông nhẹ nhàng nhưng đầy tốc độ, phù hợp mọi lứa tuổi.",
    tennisDesc: "Môn thể thao đối kháng cá nhân hoặc đôi, đòi hỏi sức bền và kỹ thuật.",
    tableTennisDesc: "Bóng bàn đòi hỏi phản xạ siêu nhanh và chiến thuật thông minh.",
    runningDesc: "Chạy bộ đơn giản nhưng hiệu quả cao, nâng cao sức bền và tim mạch.",
    cyclingDesc: "Đạp xe kết hợp thể thao và khám phá, thân thiện với môi trường.",
    swimmingDesc: "Bơi lội rèn luyện toàn thân, an toàn và hiệu quả cho sức khỏe.",
  },
  en: {
    // Nav
    findMatch: "Find Match",
    createMatch: "Create Match",
    login: "Sign in",
    logout: "Sign out",
    profile: "Profile",
    online: "Online",
    offline: "Offline",
    notifications: "Notifications",

    // Hero
    heroTitle: "Connect teammates,",
    heroTitle2: "conquer your passion",
    heroSub: "Find sports teammates near you — fast, easy, and fun.",
    heroCreate: "Create a match",
    heroFind: "Find matches",

    // Match
    matchOpen: "Open match",
    matchFull: "Full team",
    missingCount: "needed",
    joinMatch: "Join this match",
    leaveMatch: "Leave match",
    deleteMatch: "Delete match",
    shareMatch: "Share match",
    viewDetail: "View details",
    joinSuccess: "Joined match successfully! 🎉",
    leaveSuccess: "Left match successfully!",
    deleteSuccess: "Match deleted successfully",
    createSuccess: "Match created successfully! 🎉",
    copiedLink: "Match link copied! 🔗",
    cantJoin: "Cannot join match",
    cantLeave: "Cannot leave match",
    needLoginCreate: "You need to sign in to create a match.",
    needLoginSave: "Please sign in to save your profile.",
    today: "📅 Today",
    thisWeek: "📆 This week",
    weekend: "🎉 Weekend",
    all: "⏰ All",
    todayMatches: "Today's matches",
    noMatches: "No matches found",
    collapse: "Collapse",

    // Create form
    sport: "Sport",
    chooseSport: "Choose a sport...",
    chooseSportShort: "Sport...",
    title: "Match title",
    titlePlaceholder: "E.g. Friday afternoon football",
    time: "Time",
    location: "Location",
    locationPlaceholder: "Or enter address manually...",
    missingPlayers: "Players needed",
    howManyMissing: "How many players needed?",
    requirements: "Teammate requirements",
    requirementsPlaceholder: "E.g. Looking for experienced players, friendly, age 18–25, good teamwork...",
    requirementsHint: "This will be shown on the match card so players can read and decide to join.",
    submitCreate: "Create Match",
    chooseSportFirst: "Please choose a sport",
    chooseTimeFirst: "Please choose a time",
    chooseLocationFirst: "Please enter a location",
    missingPositive: "Players needed must be a positive integer",
    useMyLocation: "📍 Use my location",
    closePitchList: "Close venue list",
    nearestFirst: " — nearest first",
    locationDenied: "Location access was denied",
    locationFailed: "Cannot get location. Try again later.",
    gpsNotSupported: "GPS not supported on this device",
    locating: "Locating...",
    openMap: "Open map",
    chooseDistrict: "Choose district...",

    // Profile
    noName: "No name yet",
    shortBio: "Short description about yourself...",
    save: "Save",
    saveSuccess: "Profile saved successfully!",
    uploadPhoto: "📷 Upload photo",
    autoGenerate: "🎲 Auto generate",
    student: "Student",
    skills: "Skills",

    // Check-in
    checkin: "✓ Check-in",
    showQR: "Show Check-in QR Code",
    pasteQR: "Paste QR code here...",
    invalidQR: "Invalid QR code",
    wrongMatchQR: "QR code does not belong to this match",
    checkinSuccess: "Checked in successfully! ✅",
    alreadyCheckin: "Already checked in. You checked in before!",
    cantCheckin: "Cannot access camera. Please grant camera permission.",

    // Rating
    sendRating: "Send rating",
    ratingComment: "Comment (optional)...",
    ratingSuccess: "Rating submitted!",
    alreadyRated: "Already rated!",
    cantRate: "Cannot submit rating.",

    // Match with / ranking
    matched: "Match ✓",
    matchedDone: "✓ Matched!",
    justNow: "Just now",
    searchByName: "Search by name...",
    clearSearch: "Clear search",

    // Chat
    messages: "Messages",
    sendMessage: "Send",
    messageInput: "Type a message...",
    selectContact: "Select someone to message",
    searchUser: "🔍 Search users...",
    noContacts: "No teammates yet",
    noResults: "No users found",
    icebreaker: "🎯 Break the ice!",
    icebreakerSub: "Choose a question to start",
    sent: "✓ Sent",
    seen: "✓✓ Seen",
    newMessage: "New message 💬",

    // News
    news: "Sports highlights",
    close: "Close",

    // Sport descriptions
    soccerDesc: "The king of sports with 11 players per team, combining individual skill and teamwork.",
    futsalDesc: "Small court, high pace, refined technique and good coordination required.",
    basketballDesc: "Fast-paced basketball requiring teamwork and shooting skills.",
    volleyballDesc: "Volleyball requires teamwork and quick reflexes, popular among students.",
    badmintonDesc: "Light yet fast-paced, suitable for all ages.",
    tennisDesc: "Individual or doubles sport requiring endurance and technique.",
    tableTennisDesc: "Table tennis demands lightning-fast reflexes and smart tactics.",
    runningDesc: "Simple yet highly effective, improves endurance and cardiovascular health.",
    cyclingDesc: "Combines sport and exploration, eco-friendly.",
    swimmingDesc: "Full-body workout, safe and effective for health.",
  },
} as const;

export type TranslationKey = keyof typeof translations.vi;
